# name: Price Check

# on:
#   schedule:
#     - cron: '0 */6 * * *'
#   workflow_dispatch:

# jobs:
#   check-prices:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |gi
#           pip install playwright python-dotenv requests

#       - name: Install Playwright browsers
#         run: playwright install chromium

#       - name: Run price check
#         env:
#           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#           CHAT_ID: ${{ secrets.CHAT_ID }}
#         run: python main.py
